apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
  namespace: app-service
spec:
  schedule: "*/1 * * * *"  
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: app-cronjob-container
            image: busybox
            command: ["echo", "This is a cron job running every minute"]
          restartPolicy: OnFailure
