apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: app-daemon
  namespace: app-service
spec:
  selector:
    matchLabels:
      app: app-daemon
  template:
    metadata:
      labels:
        app: app-daemon
    spec:
      containers:
      - name: app-daemon-container
        image: nginx:latest
        ports:
        - containerPort: 80
