apiVersion: batch/v1
kind: Job
metadata:
  name: app-job
  namespace: app-service
spec:
  template:
    spec:
      containers:
      - name: app-job-container
        image: busybox
        command: ["echo", "Hello, Kubernetes!"]
      restartPolicy: Never
  backoffLimit: 4
