apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: app-rplc
  namespace: app-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-rplc
  template:
    metadata:
      labels:
        app: app-rplc
    spec:
      containers:
      - name: app-container
        image: nginx:latest
        ports:
        - containerPort: 80
