apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: app-service
spec:
  selector:
    matchLabels:
      app: mariadb
  serviceName: "mariadb-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        env:
        - name: root
          value: ""  
        ports:
        - containerPort: 3306
       